spring:
  datasource:
    url: jdbc:sqlite:src/main/resources/huazhu.sqlite3
    driverClassName: org.sqlite.JDBC
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLiteDialect
        format_sql: true
    generate-ddl: true
    hibernate.ddl-auto: update
    show-sql: false
    open-in-view: true
  # logging.level.org.hibernate.type.descriptor.sql.BasicBinder=trace
bot:
  cacheDir: J:\tools\code\huazhu\cache
#  workingDir: J:\tools\code\huazhu\workingDir
